FunnyUsers/FunnyUsers/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace FunnyUsers.Controllers
{

        public class RoleController : Controller
        {
            RoleManager<IdentityRole> roleManager;


            public RoleController(RoleManager<IdentityRole> roleManager)
            {
                this.roleManager = roleManager;
            }

            //[Authorize(Policy ="writepolicy")] --working fine as well.
            [Authorize(Roles = "Manager,Administrator")]
            public IActionResult Index()
            {
                var roles = roleManager.Roles.ToList();
                

                return View(roles);
            }



            [Authorize(Roles = "Manager,Administrator")]
            //[Authorize(Policy ="readpolicy")]
            public IActionResult Create()
            {
                return View(new IdentityRole());
            }


            [HttpPost]
            public async Task<IActionResult> Create(IdentityRole role)
            {
                await roleManager.CreateAsync(role);
                return RedirectToAction("Index");
            }
        }
    
}

FunnyUsers/FunnyUsers/Controllers/UsersController.cs
using FunnyUsers.Areas.Identity.Pages.Account;
using FunnyUsers.Data;
using FunnyUsers.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace FunnyUsers.Controllers
{
    public class UsersController : Controller
    {
        //UserManager<IdentityUser> _userManager;
        UserManager<IdentityUser> _userManager;
        SignInManager<IdentityUser> _signInManager;
        ApplicationDbContext _db;
        RoleManager<IdentityRole> _roleManager;
        //public ApplicationUser _appUser { get; set; }
        public CreateUserModel createModel { get; set; }


        public UsersController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, ApplicationDbContext db, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _db = db;
            _roleManager = roleManager;
        }



        public IActionResult Index()
        {
            return View(_db.ApplicationUsers.ToList()); //works fine
            //return View(_userManager.Users.ToList());
        }


        public async Task<ActionResult> Create()
        {
            //this uses a redirect from View to Register.cshtml from Identity area
            return View();


        }





        //public IActionResult Edit(string userID) // need to make it string due to IdentityUser<string>
        //{
        //
        //    var user = _db.ApplicationUsers.Where(u => u.Id == userID).FirstOrDefault();
        //   // var user = _db.ApplicationUsers.ToList();
        //    return View(user);
        //}


        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            var userToEdit = _db.ApplicationUsers.Where(p => p.Id == id).FirstOrDefault();
            return View(userToEdit);
            //var user = new ApplicationUser()
            //{
            //    UserName = userToEdit.UserName,
            //    Email = userToEdit.Email,
            //    Department = userToEdit.Department,
            //    Role = userToEdit.Role
            //};
            //
            //return View(user);
        } //works, leave it that way

        [HttpPost]
        public async Task<ActionResult> Edit(ApplicationUser model)
        {
            var userToEdit = _db.ApplicationUsers.Where(p => p.Id == model.Id).FirstOrDefault();

            userToEdit.UserName = model.UserName;
            userToEdit.Email = model.Email;
            userToEdit.Department = model.Department;
            userToEdit.Role = model.Role;

            var result = await _userManager.UpdateAsync(userToEdit);


            if (result.Succeeded)
            {
                return RedirectToAction("Index", _db.ApplicationUsers.ToList());
            }



            return View(model);
            //return RedirectToAction("Index", _db.ApplicationUsers.ToList());
        }

        /* WORKS FINE BUT NEED TO EDIT THE "EDIT" VIEW as it not takes the POST, it's taking it only if you INPUT it manually in URL*/

        [HttpPost]
        public async Task<ActionResult> DeleteUser(string id)
        {
            var user = _db.ApplicationUsers.Where(p => p.Id == id).FirstOrDefault();
            
            var result = await _userManager.DeleteAsync(user);

            return View("Index", _db.ApplicationUsers.ToList());


        }

    }
}

FunnyUsers/FunnyUsers/Views/Shared/_ButtonPartial.cshtml
@model int

<td style="width:150px">
    <div class="btn-group">
        <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model">
            <i class="far fa-edit"></i>
        </a>

        <a asp-action="Details" class="btn btn-success" asp-route-id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>

    </div>

</td>

FunnyUsers/FunnyUsers/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Users</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Users</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <!--<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>-->
                        <!-- Adding the role Index.cshtml to be visible on the main layout-->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                        </li>

                        <!-- Manager and/or Administrator to see the register -->
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Administrator") || User.IsInRole("Manager"))
                        {
                            <li class="nav-item">
                                <!-- <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a> -->
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">ListUser</a>
                            </li>



                        }



                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Users - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

FunnyUsers/FunnyUsers/Views/Shared/_PartialView.cshtml
@model string

<td style="width:150px">
    <div class="btn-group">
        <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model">
            <i class="btn btn-info"></i>
        </a>

        <a asp-action="DeleteUser" class="btn btn-success" asp-route-id="@Model">
            <i class="btn btn-danger"></i>
        </a>

    </div>

</td>